name: Deployment
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: python:3.12-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build package
        run: pip install build && python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
