name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-alpine
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version
        id: get_version
        run: |
          version=$(grep "__version__ =" flatdict2.py | sed -E "s/__version__ = '([0-9]+\.[0-9]+\.[0-9]+)'/\1/")
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}