name: Testing
on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'setup.*'
      - '*.md'
      - '*.rst'
    branches-ignore: [ main ]
    tags-ignore: ["*"]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.5', '3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
    container:
      image: python:${{ matrix.python }}-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install codecov dependancies
        run: apk add curl gnupg coreutils git

      - name: Bootstrap the test environment
        run: pip install -r requires/testing.txt && mkdir -p build

      - name: Run flake8 tests
        run: flake8

      - name: Run unittests
        run: coverage run && coverage report && coverage xml

      - name: Upload Coverage
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: build/coverage.xml
